### ISSUE TITLE
Issue with large messages and custom messages on rosserial_xbee

### ISSUE THREAD

**Issue by tonybaltovski** [ros-drivers/rosserial-experimental#2]
I am trying to use the rosserial_xbee node that I installed using rosbuild.  For the most part it works well.  However, when I try to use large messages such as geometry_msgs::TransformStamped, I get the following error:

[INFO] [WallTime: 1370291029.222352] Failed Packet Flags 
[INFO] [WallTime: 1370291029.323173] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1370291029.369326] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1370291029.415304] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1370291029.450804] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1370291029.488945] Packet Failed :  Failed to read msg data
[INFO] [WallTime: 1370291029.524294] Packet Failed :  Failed to read msg data
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/t510/catkin_ws/src/rosserial/rosserial_python/src/rosserial_python/SerialClient.py", line 387, in run
    checksum = sum(map(ord,header) ) + sum(map(ord, msg)) + ord(chk)
TypeError: ord() expected a character, but string of length 0 found

This only occurs when a large message is used.  Small messages work such as the HelloWorld and pubsub sketches provided in the rosserial_arduino libraries.   I am using an Arduino Mega.  Any ideas?  

Thank you,

Tony

**Comment by mikeferguson** [comment]
How large is large? Is it possible the message is actually too large to be serialized without running out of memory?

**Comment by tonybaltovski** [comment]
It is the custom message with header and 3 vector3 variables.  When I use a direct connection it works just fine but the rosserial_xbee gives me that error.  I reduced the publisher and subscriber buffer size to 101 bytes each in the ros.h of the sketch since the xbee has a buffer of 202 bytes.  It works with the reduced buffer size when directly connected.

Thank you Mike.

Tony

**Comment by tonybaltovski** [comment]
Adding a larger delay fixed this problem.
